from fastapi import Depends, HTTPException, status
from fastapi.security import OAuth2PasswordBearer
from jose import JWTError, jwt
from motor.motor_asyncio import AsyncIOMotorDatabase
from app.database import get_database
from app.config import settings
from typing import Dict, Any

oauth2_scheme = OAuth2PasswordBearer(tokenUrl="api/v1/auth/login")
from app.database import get_database

async def get_db(db: AsyncIOMotorDatabase = Depends(get_database)) -> AsyncIOMotorDatabase:
    return db

async def get_current_user(token: str = Depends(oauth2_scheme), db: AsyncIOMotorDatabase = Depends(get_db)) -> Dict[str, Any]:
    credentials_exception = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Could not validate credentials",
        headers={"WWW-Authenticate": "Bearer"},
    )
    try:
        payload = jwt.decode(token, settings.JWT_SECRET_KEY, algorithms=[settings.JWT_ALGORITHM])
        user_id: str = payload.get("sub")
        if user_id is None:
            raise credentials_exception
    except JWTError:
        raise credentials_exception
        
    user = await db.users.find_one({"_id": user_id})
    # If using string ids we might need to convert depending on how insert was done,
    # In auth_service we used str(inserted_id). So querying by string or ObjectId might be needed.
    # Note: In auth_service we inserted using `by_alias=True`, but the ID was generated by mongo
    # and we saved it as a string in the JWT token.
    # If the user is not found by string, try ObjectId.
    from bson import ObjectId
    if not user:
        try:
            user = await db.users.find_one({"_id": ObjectId(user_id)})
        except Exception:
            raise credentials_exception
            
    if user is None:
        raise credentials_exception
        
    return user
